import type { CompiledContext } from "@/types";
import type { ReviewCompiler } from "@/review/types";

function buildPathInstructions(contexts: CompiledContext[]): Array<{ path: string; instructions: string }> {
  const pathMap = new Map<string, string[]>();

  for (const ctx of contexts) {
    for (const g of ctx.guidelines) {
      for (const p of g.paths) {
        const rules = pathMap.get(p) ?? [];
        if (!rules.includes(g.rule)) rules.push(g.rule);
        pathMap.set(p, rules);
      }
    }
  }

  const sorted = [...pathMap.keys()].sort((a, b) => {
    if (a === "**") return -1;
    if (b === "**") return 1;
    return a.localeCompare(b);
  });

  return sorted.map((path) => ({
    path,
    instructions: pathMap.get(path)!.map((r) => `- ${r}`).join("\n"),
  }));
}

export const coderabbitCompiler: ReviewCompiler = {
  target: "coderabbit",
  outputPath: ".coderabbit.yaml",

  compile(contexts: CompiledContext[]): string {
    const entries = buildPathInstructions(contexts);
    if (entries.length === 0) return "";

    const lines: string[] = [];
    lines.push("# Generated by agsync sync. Do not edit manually.");
    lines.push("reviews:");
    lines.push("  path_instructions:");

    for (const entry of entries) {
      lines.push(`    - path: "${entry.path}"`);
      lines.push(`      instructions: |`);
      for (const rule of entry.instructions.split("\n")) {
        lines.push(`        ${rule}`);
      }
    }

    return lines.join("\n") + "\n";
  },
};
