import {
  mkdir, writeFile, readFile, rm, readdir,
  stat as fsStat, copyFile, symlink, lstat, readlink,
} from "node:fs/promises";
import { resolve, dirname, relative } from "node:path";
import { stringify as toToml } from "smol-toml";
import { loadHierarchicalConfig, findGitRoot } from "@/loader/hierarchy";
import { resolveAllSkills } from "@/resolver/skills";
import { resolveAgentConfig } from "@/agents/registry";
import { runValidate } from "@/commands/validate";
import { expandToolEnv } from "@/utils/env";
import { readLockFile, writeLockFile } from "@/lock/lock";
import type {
  ResolvedSkill, SyncPlan, PlannedFile, PlannedSkill,
  ToolDefinition, AgentConfig, AgentMcpFeatureConfig, CommandDefinition,
  GitignoreMode, ResolvedAgentConfig, LockFile, ScopedContent,
} from "@/types";

function managedFooter(sourcePath: string): string {
  return `\n<!-- DO NOT EDIT THIS FILE. Edit: ${sourcePath} -->\n`;
}

export function skillDirName(name: string): string {
  return name.replace(/:/g, "--");
}

function skillSourcePath(skill: ResolvedSkill): string {
  const baseName = skill.name.includes(":") ? skill.name.split(":").pop()! : skill.name;
  if (skill.scope) {
    return `${skill.scope}/.agsync/skills/${baseName}/SKILL.md`;
  }
  return `.agsync/skills/${baseName}/SKILL.md`;
}

function buildOutputSkillMd(skill: ResolvedSkill, tools: ToolDefinition[]): string {
  const lines: string[] = [];

  lines.push("---");
  lines.push(`name: ${skill.name}`);
  lines.push(`description: ${skill.description}`);
  if (skill.scope) {
    lines.push(`scope: ${skill.scope}`);
  }
  lines.push("---");
  lines.push("");

  lines.push(skill.instructions.trim());

  if (skill.tools.length > 0) {
    lines.push("");
    lines.push("## Available Tools");
    lines.push("");
    for (const toolName of skill.tools) {
      const tool = tools.find((t) => t.name === toolName);
      if (tool) {
        lines.push(`- **${tool.name}**: ${tool.description}`);
      } else {
        lines.push(`- ${toolName}`);
      }
    }
  }

  if (skill.scope) {
    lines.push("");
    lines.push(`> **Scope: NEVER use this skill outside of \`${skill.scope}\`.**`);
  }

  return lines.join("\n") + managedFooter(skillSourcePath(skill));
}

function buildAgentsMd(
  userInstructions: string,
  skills: ResolvedSkill[],
  scopeRefs: string[] = [],
  sourcePath = ".agsync/instructions.md"
): string {
  const lines: string[] = [];

  if (userInstructions.trim()) {
    lines.push(userInstructions.trim());
    lines.push("");
  }

  lines.push("<!-- agsync:begin -->");
  lines.push("## Available Skills");
  lines.push("");

  const globalSkills = skills.filter((s) => !s.scope);
  const scopedSkills = skills.filter((s) => s.scope);

  for (const skill of globalSkills) {
    lines.push(`- **${skill.name}**: ${skill.description}`);
  }

  if (scopedSkills.length > 0) {
    const byScope = new Map<string, ResolvedSkill[]>();
    for (const skill of scopedSkills) {
      const group = byScope.get(skill.scope!) ?? [];
      group.push(skill);
      byScope.set(skill.scope!, group);
    }
    for (const [scope, group] of byScope) {
      lines.push("");
      lines.push(`### Scope: \`${scope}\``);
      lines.push("");
      for (const skill of group) {
        lines.push(`- **${skill.name}**: ${skill.description}`);
      }
    }
  }

  if (scopeRefs.length > 0) {
    lines.push("");
    lines.push("## Scoped Instructions");
    lines.push("");
    for (const ref of scopeRefs) {
      lines.push(`- When working in folder: \`${ref}\` — you MUST load \`${ref}/AGENTS.md\``);
    }
  }

  lines.push("");
  lines.push("Skills are managed by agsync. Full definitions are in `.agents/skills/`.");
  lines.push("<!-- agsync:end -->");

  return lines.join("\n") + managedFooter(sourcePath);
}

function buildScopedAgentsMd(
  scope: ScopedContent,
  skills: ResolvedSkill[]
): string {
  const lines: string[] = [];
  const sourcePath = `${scope.scope}/.agsync/instructions.md`;

  if (scope.instructions.trim()) {
    lines.push(scope.instructions.trim());
    lines.push("");
  }

  const scopeSkills = skills.filter((s) => s.scope === scope.scope);
  if (scopeSkills.length > 0) {
    lines.push("<!-- agsync:begin -->");
    lines.push("## Available Skills");
    lines.push("");
    for (const skill of scopeSkills) {
      lines.push(`- **${skill.name}**: ${skill.description}`);
    }
    lines.push("");
    lines.push("Skills are managed by agsync. Full definitions are in `.agents/skills/`.");
    lines.push("<!-- agsync:end -->");
  }

  return lines.join("\n") + managedFooter(sourcePath);
}

function commandSourcePath(cmd: CommandDefinition): string {
  if (cmd.scope) {
    return `${cmd.scope}/.agsync/commands/${cmd.name.includes(":") ? cmd.name.split(":").pop() : cmd.name}.md`;
  }
  return `.agsync/commands/${cmd.name}.md`;
}

function buildOutputCommand(cmd: CommandDefinition): string {
  let content = cmd.content;
  if (cmd.scope) {
    content += `\n\n> **Scope: NEVER use this command outside of \`${cmd.scope}\`.**`;
  }
  return content + managedFooter(commandSourcePath(cmd));
}

function buildMcpServersObject(tools: ToolDefinition[]): Record<string, unknown> {
  const servers: Record<string, unknown> = {};
  for (const tool of tools) {
    if (tool.type !== "mcp") continue;
    servers[tool.name] = {
      command: tool.command ?? "",
      args: tool.args ?? [],
      env: tool.env ?? {},
    };
  }
  return servers;
}

function serializeMcpJson(
  rootKey: string,
  servers: Record<string, unknown>
): string {
  return JSON.stringify({ [rootKey]: servers }, null, 2);
}

function serializeMcpToml(
  rootKey: string,
  servers: Record<string, unknown>
): string {
  return toToml({ [rootKey]: servers });
}

function mergeJsonContent(existing: string, incoming: string, rootKey: string): string {
  try {
    const existingObj = JSON.parse(existing);
    const incomingObj = JSON.parse(incoming);
    existingObj[rootKey] = { ...(existingObj[rootKey] ?? {}), ...incomingObj[rootKey] };
    return JSON.stringify(existingObj, null, 2);
  } catch {
    return incoming;
  }
}

async function readFileOrEmpty(filePath: string): Promise<string> {
  try {
    return await readFile(filePath, "utf-8");
  } catch {
    return "";
  }
}

async function listSubdirectories(dir: string): Promise<string[]> {
  try {
    const entries = await readdir(dir);
    const dirs: string[] = [];
    for (const entry of entries) {
      const s = await fsStat(resolve(dir, entry));
      if (s.isDirectory()) dirs.push(entry);
    }
    return dirs;
  } catch {
    return [];
  }
}

export async function buildSyncPlan(
  targetDir: string,
  options?: { expandEnv?: boolean; frozen?: boolean }
): Promise<SyncPlan> {
  const allErrors = await runValidate(targetDir);
  const hardErrors = allErrors.filter((e) => e.severity !== "warn");
  if (hardErrors.length > 0) {
    const messages = hardErrors.map((e) => `  ${e.file}: ${e.message}`).join("\n");
    throw new Error(`Validation failed:\n${messages}`);
  }

  const loaded = await loadHierarchicalConfig(targetDir);
  if (!loaded) {
    throw new Error("No agsync.yaml found");
  }

  const baseDir = dirname(loaded.configPath);
  const frozen = options?.frozen ?? false;
  const lock = await readLockFile(baseDir);

  if (frozen && !lock) {
    throw new Error("--frozen: agsync-lock.yaml not found");
  }

  const skillsDir = resolve(baseDir, ".agsync", "skills");
  const resolveResult = await resolveAllSkills(loaded.skills, skillsDir, { lock, frozen });
  const resolvedSkills = resolveResult.skills;

  let tools = loaded.tools;
  const warnings: string[] = [];
  if (options?.expandEnv !== false) {
    const expanded = expandToolEnv(loaded.tools);
    tools = expanded.tools;
    for (const w of expanded.warnings) {
      warnings.push(`Environment variable "${w.varName}" is not set (tool "${w.tool}", key "${w.key}")`);
    }
  }

  const agents = resolveAgentConfig(loaded.config.agents, loaded.config.features);
  const commands = loaded.commands;

  const gitRoot = findGitRoot(targetDir);
  const canonicalSkillsDir = resolve(gitRoot, ".agents", "skills");
  const canonicalCommandsDir = resolve(gitRoot, ".agents", "commands");
  const skillOutputDirs = [canonicalSkillsDir];

  const definedSkillDirNames = new Set(resolvedSkills.map((s) => skillDirName(s.name)));
  const existingSkillNames = new Set<string>();
  for (const name of await listSubdirectories(canonicalSkillsDir)) {
    existingSkillNames.add(name);
  }

  const plannedSkills: PlannedSkill[] = [];
  for (const skill of resolvedSkills) {
    const dirName = skillDirName(skill.name);
    plannedSkills.push({
      name: dirName,
      operation: existingSkillNames.has(dirName) ? "update" : "create",
      sourceDir: skill.sourceDir,
    });
  }
  for (const name of existingSkillNames) {
    if (!definedSkillDirNames.has(name)) {
      plannedSkills.push({ name, operation: "delete" });
    }
  }

  const plannedFiles: PlannedFile[] = [];

  for (const skill of resolvedSkills) {
    const dirName = skillDirName(skill.name);
    const skillMdPath = resolve(canonicalSkillsDir, dirName, "SKILL.md");
    const content = buildOutputSkillMd(skill, tools);
    const existing = await readFileOrEmpty(skillMdPath);
    plannedFiles.push({
      path: skillMdPath,
      content,
      existing,
      operation: !existing ? "create" : content !== existing ? "update" : "unchanged",
    });
  }

  for (const cmd of commands) {
    const cmdDirName = skillDirName(cmd.name);
    const cmdPath = resolve(canonicalCommandsDir, `${cmdDirName}.md`);
    const content = buildOutputCommand(cmd);
    const existing = await readFileOrEmpty(cmdPath);
    plannedFiles.push({
      path: cmdPath,
      content,
      existing,
      operation: !existing ? "create" : content !== existing ? "update" : "unchanged",
    });
  }

  const scopes = loaded.scopes ?? [];
  const scopeRefs = scopes
    .filter((s) => s.instructions.trim().length > 0 || s.skills.length > 0)
    .map((s) => s.scope);

  const instructionsPath = resolve(baseDir, ".agsync", "instructions.md");
  const userInstructions = await readFileOrEmpty(instructionsPath);
  const agentsMdPath = resolve(gitRoot, "AGENTS.md");
  const agentsMdContent = buildAgentsMd(userInstructions, resolvedSkills, scopeRefs);
  const existingAgentsMd = await readFileOrEmpty(agentsMdPath);
  plannedFiles.push({
    path: agentsMdPath,
    content: agentsMdContent,
    existing: existingAgentsMd,
    operation: !existingAgentsMd ? "create" : agentsMdContent !== existingAgentsMd ? "update" : "unchanged",
  });

  for (const scope of scopes) {
    if (!scope.instructions.trim() && scope.skills.length === 0) continue;
    const scopeAgentsMdPath = resolve(scope.dir, "AGENTS.md");
    const scopeContent = buildScopedAgentsMd(scope, resolvedSkills);
    const existingScopeAgentsMd = await readFileOrEmpty(scopeAgentsMdPath);
    plannedFiles.push({
      path: scopeAgentsMdPath,
      content: scopeContent,
      existing: existingScopeAgentsMd,
      operation: !existingScopeAgentsMd ? "create" : scopeContent !== existingScopeAgentsMd ? "update" : "unchanged",
    });
  }

  for (const [agentName, agentCfg] of Object.entries(agents)) {
    planAgentFeatures(agentName, agentCfg, gitRoot, agentsMdPath, canonicalSkillsDir, canonicalCommandsDir, tools, plannedFiles);
  }

  const symlinkErrors = await validateSymlinkTargets(plannedFiles);
  if (symlinkErrors.length > 0) {
    throw new Error(
      `Sync blocked — target paths are not empty:\n${symlinkErrors.map(e => `  ${e}`).join("\n")}`
    );
  }

  return {
    skills: plannedSkills,
    files: plannedFiles,
    skillOutputDirs,
    canonicalSkillsDir: skillsDir,
    warnings,
    lockUpdates: resolveResult.lockUpdates,
  };
}

function planAgentFeatures(
  _agentName: string,
  config: AgentConfig,
  targetDir: string,
  agentsMdPath: string,
  canonicalSkillsDir: string,
  canonicalCommandsDir: string,
  tools: ToolDefinition[],
  files: PlannedFile[]
): void {
  if (config.instructions?.enabled) {
    const dest = resolve(targetDir, config.instructions.destination);
    if (dest !== agentsMdPath) {
      const symlinkTarget = relative(dirname(dest), agentsMdPath);
      files.push({
        path: dest,
        content: "",
        existing: "",
        operation: "create",
        symlink: symlinkTarget,
      });
    }
  }

  if (config.skills?.enabled) {
    const dest = resolve(targetDir, config.skills.destination);
    if (dest !== canonicalSkillsDir) {
      const symlinkTarget = relative(dirname(dest), canonicalSkillsDir);
      files.push({
        path: dest,
        content: "",
        existing: "",
        operation: "create",
        symlink: symlinkTarget,
      });
    }
  }

  if (config.commands?.enabled) {
    const dest = resolve(targetDir, config.commands.destination);
    if (dest !== canonicalCommandsDir) {
      const symlinkTarget = relative(dirname(dest), canonicalCommandsDir);
      files.push({
        path: dest,
        content: "",
        existing: "",
        operation: "create",
        symlink: symlinkTarget,
      });
    }
  }

  if (config.mcp?.enabled) {
    const mcpConfig = config.mcp as AgentMcpFeatureConfig;
    const dest = resolve(targetDir, mcpConfig.destination);
    const mcpTools = tools.filter((t) => t.type === "mcp");
    if (mcpTools.length > 0) {
      const servers = buildMcpServersObject(mcpTools);
      const { format, root_key } = mcpConfig.mcp_format;
      const content = format === "toml"
        ? serializeMcpToml(root_key, servers)
        : serializeMcpJson(root_key, servers);

      files.push({
        path: dest,
        content,
        existing: "",
        operation: "create",
      });
    }
  }
}

async function validateSymlinkTargets(files: PlannedFile[]): Promise<string[]> {
  const errors: string[] = [];
  for (const file of files) {
    if (!file.symlink) continue;
    try {
      const s = await lstat(file.path);
      if (s.isSymbolicLink()) continue;
      if (s.isDirectory()) {
        const entries = await readdir(file.path);
        if (entries.length > 0) {
          errors.push(
            `"${file.path}" is a non-empty directory — remove its contents or delete it before syncing`
          );
        }
      } else {
        errors.push(
          `"${file.path}" already exists as a regular file — remove it before syncing`
        );
      }
    } catch {
      // does not exist — OK
    }
  }
  return errors;
}

async function copyDirRecursive(
  srcDir: string,
  destDir: string,
  skipFiles: Set<string>
): Promise<string[]> {
  const copied: string[] = [];
  let entries: string[];
  try {
    entries = await readdir(srcDir);
  } catch {
    return copied;
  }

  for (const entry of entries) {
    if (skipFiles.has(entry)) continue;

    const srcPath = resolve(srcDir, entry);
    const destPath = resolve(destDir, entry);
    const s = await fsStat(srcPath);

    if (s.isDirectory()) {
      await mkdir(destPath, { recursive: true });
      const nested = await copyDirRecursive(srcPath, destPath, new Set());
      copied.push(...nested);
    } else if (s.isFile()) {
      await mkdir(dirname(destPath), { recursive: true });
      await copyFile(srcPath, destPath);
      copied.push(destPath);
    }
  }

  return copied;
}

async function copySupportingFiles(plan: SyncPlan): Promise<string[]> {
  const copied: string[] = [];
  const canonicalOutputDir = plan.skillOutputDirs[0];
  if (!canonicalOutputDir) return copied;

  const activeSkills = plan.skills.filter((s) => s.operation !== "delete");

  for (const skill of activeSkills) {
    const sourceDir = skill.sourceDir ?? resolve(plan.canonicalSkillsDir, skill.name);
    try {
      await fsStat(sourceDir);
    } catch {
      continue;
    }

    const baseName = skill.name.includes("--") ? skill.name.split("--").pop()! : skill.name;
    const skipFiles = new Set(["SKILL.md", `${baseName}.yaml`]);
    const targetOutputDir = resolve(canonicalOutputDir, skill.name);
    const files = await copyDirRecursive(sourceDir, targetOutputDir, skipFiles);
    copied.push(...files);
  }

  return copied;
}

async function ensureSymlink(linkPath: string, target: string): Promise<void> {
  try {
    const s = await lstat(linkPath);
    if (s.isSymbolicLink()) {
      const existingTarget = await readlink(linkPath);
      if (existingTarget === target) return;
      await rm(linkPath);
    } else {
      await rm(linkPath, { recursive: true, force: true });
    }
  } catch {
    // path doesn't exist
  }
  await mkdir(dirname(linkPath), { recursive: true });
  const isFile = target.endsWith(".md") || target.endsWith(".json") || target.endsWith(".toml");
  await symlink(target, linkPath, isFile ? "file" : "dir");
}

async function applyMcpFile(file: PlannedFile): Promise<void> {
  const existing = await readFileOrEmpty(file.path);
  let content = file.content;

  if (existing && file.path.endsWith(".json")) {
    try {
      const parsed = JSON.parse(file.content);
      const rootKey = Object.keys(parsed)[0];
      if (rootKey) {
        content = mergeJsonContent(existing, file.content, rootKey);
      }
    } catch {
      // use incoming as-is
    }
  }

  await mkdir(dirname(file.path), { recursive: true });
  await writeFile(file.path, content, "utf-8");
}

async function applySyncPlan(plan: SyncPlan): Promise<string[]> {
  const staleSkills = plan.skills.filter((s) => s.operation === "delete");
  for (const skill of staleSkills) {
    for (const dir of plan.skillOutputDirs) {
      await rm(resolve(dir, skill.name), { recursive: true, force: true });
    }
  }

  const written: string[] = [];
  for (const file of plan.files) {
    if (file.operation === "delete" || file.operation === "unchanged") continue;

    if (file.symlink) {
      await ensureSymlink(file.path, file.symlink);
      written.push(file.path);
      continue;
    }

    if (isMcpFile(file.path)) {
      await applyMcpFile(file);
    } else {
      await mkdir(dirname(file.path), { recursive: true });
      await writeFile(file.path, file.content, "utf-8");
    }
    written.push(file.path);
  }

  const copied = await copySupportingFiles(plan);
  written.push(...copied);

  return written;
}

function isMcpFile(path: string): boolean {
  return path.endsWith("settings.json") ||
    path.endsWith("mcp.json") ||
    path.endsWith("mcp_config.json") ||
    path.endsWith(".mcp.json") ||
    path.endsWith("config.toml") ||
    path.endsWith("opencode.json");
}

const GITIGNORE_BEGIN = "# agsync:begin";
const GITIGNORE_END = "# agsync:end";

function collectGitignoreEntries(
  mode: GitignoreMode,
  agents: ResolvedAgentConfig,
  plan: SyncPlan
): string[] {
  if (mode === "off") return [];

  if (mode === "mcpOnly") {
    const entries: string[] = [];
    for (const agentCfg of Object.values(agents)) {
      if (agentCfg.mcp?.enabled) {
        entries.push(agentCfg.mcp.destination);
      }
    }
    return entries;
  }

  const entries = new Set<string>();
  entries.add("AGENTS.md");
  entries.add(".agents/");

  for (const file of plan.files) {
    if (file.path.endsWith("AGENTS.md") && !file.symlink) {
      const rel = relative(process.cwd(), file.path);
      entries.add(rel);
    }
  }

  for (const file of plan.files) {
    if (file.symlink || isMcpFile(file.path)) {
      const rel = relative(process.cwd(), file.path);
      entries.add(rel.startsWith(".") ? rel : rel);
    }
  }

  for (const agentCfg of Object.values(agents)) {
    if (agentCfg.instructions?.enabled) entries.add(agentCfg.instructions.destination);
    if (agentCfg.skills?.enabled) entries.add(agentCfg.skills.destination);
    if (agentCfg.commands?.enabled) entries.add(agentCfg.commands.destination);
    if (agentCfg.mcp?.enabled) entries.add(agentCfg.mcp.destination);
  }

  return [...entries].sort();
}

function updateGitignoreContent(existing: string, entries: string[]): string {
  const beginIdx = existing.indexOf(GITIGNORE_BEGIN);
  const endIdx = existing.indexOf(GITIGNORE_END);

  const section = entries.length > 0
    ? [GITIGNORE_BEGIN, ...entries, GITIGNORE_END].join("\n")
    : "";

  if (beginIdx !== -1 && endIdx !== -1) {
    const before = existing.slice(0, beginIdx);
    const after = existing.slice(endIdx + GITIGNORE_END.length);
    if (!section) {
      return (before + after).replace(/\n{3,}/g, "\n\n").trim() + "\n";
    }
    return before + section + after;
  }

  if (!section) return existing;

  if (existing.length > 0 && !existing.endsWith("\n")) {
    return existing + "\n\n" + section + "\n";
  }
  if (existing.length > 0) {
    return existing + "\n" + section + "\n";
  }
  return section + "\n";
}

async function manageGitignore(
  targetDir: string,
  mode: GitignoreMode,
  agents: ResolvedAgentConfig,
  plan: SyncPlan
): Promise<string | null> {
  const entries = collectGitignoreEntries(mode, agents, plan);

  if (mode === "off" && entries.length === 0) {
    const gitignorePath = resolve(targetDir, ".gitignore");
    const existing = await readFileOrEmpty(gitignorePath);
    if (existing.includes(GITIGNORE_BEGIN)) {
      const updated = updateGitignoreContent(existing, []);
      await writeFile(gitignorePath, updated, "utf-8");
      return gitignorePath;
    }
    return null;
  }

  if (entries.length === 0) return null;

  const gitignorePath = resolve(targetDir, ".gitignore");
  const existing = await readFileOrEmpty(gitignorePath);
  const updated = updateGitignoreContent(existing, entries);

  if (updated !== existing) {
    await writeFile(gitignorePath, updated, "utf-8");
    return gitignorePath;
  }

  return null;
}

export async function runSync(
  targetDir: string,
  options?: { frozen?: boolean }
): Promise<{ written: string[]; warnings: string[] }> {
  const loaded = await loadHierarchicalConfig(targetDir);
  if (!loaded) {
    throw new Error("No agsync.yaml found");
  }

  const frozen = options?.frozen ?? false;
  const plan = await buildSyncPlan(targetDir, { frozen });
  const written = await applySyncPlan(plan);

  if (!frozen && plan.lockUpdates) {
    const baseDir = dirname(loaded.configPath);
    const existingLock = await readLockFile(baseDir);
    const newLock: LockFile = {
      lockVersion: 1,
      sources: { ...(existingLock?.sources ?? {}), ...plan.lockUpdates.sources },
      extends: { ...(existingLock?.extends ?? {}), ...plan.lockUpdates.extends },
    };
    const hasEntries = Object.keys(newLock.sources).length > 0 || Object.keys(newLock.extends).length > 0;
    if (hasEntries) {
      const lockPath = await writeLockFile(baseDir, newLock);
      written.push(lockPath);
    }
  }

  const agents = resolveAgentConfig(loaded.config.agents, loaded.config.features);
  const gitignoreResult = await manageGitignore(
    targetDir,
    loaded.config.gitignore,
    agents,
    plan
  );
  if (gitignoreResult) {
    written.push(gitignoreResult);
  }

  return { written, warnings: plan.warnings };
}
