import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { parse as parseYaml, stringify as toYaml } from "yaml";
import { lockFileSchema } from "@/lock/schema";
import type { LockFile, LockEntry } from "@/types";

const LOCK_FILENAME = "agsync-lock.yaml";

const LOCK_HEADER = "# auto-generated by agsync — do not edit\n";

export async function readLockFile(dir: string): Promise<LockFile | null> {
  const lockPath = resolve(dir, LOCK_FILENAME);
  try {
    const raw = await readFile(lockPath, "utf-8");
    const parsed = parseYaml(raw);
    return lockFileSchema.parse(parsed);
  } catch {
    return null;
  }
}

export async function writeLockFile(dir: string, lock: LockFile): Promise<string> {
  const lockPath = resolve(dir, LOCK_FILENAME);

  const sortedSources: Record<string, LockEntry> = {};
  for (const key of Object.keys(lock.sources).sort()) {
    sortedSources[key] = lock.sources[key];
  }

  const sortedExtends: Record<string, LockEntry> = {};
  for (const key of Object.keys(lock.extends).sort()) {
    sortedExtends[key] = lock.extends[key];
  }

  const ordered: LockFile = {
    lockVersion: 1,
    sources: sortedSources,
    extends: sortedExtends,
  };

  const content = LOCK_HEADER + toYaml(ordered, { lineWidth: 0 });
  await writeFile(lockPath, content, "utf-8");
  return lockPath;
}

export function isLocked(lock: LockFile, section: "sources" | "extends", key: string, version: string): boolean {
  const entry = lock[section][key];
  return !!entry && entry.version === version;
}

export function getLockEntry(lock: LockFile, section: "sources" | "extends", key: string): LockEntry | undefined {
  return lock[section][key];
}
