import type { CompiledContext, ResolvedSkill, PatternDefinition } from "@/types";

export function compileScopedAgentsMd(
  context: CompiledContext,
  skills: ResolvedSkill[],
  patternDefs: PatternDefinition[],
  opts: { isRoot?: boolean; scopeRefs?: string[] } = {}
): string {
  const { isRoot = false, scopeRefs = [] } = opts;
  const src = context.scope
    ? `${context.scope}/.agsync/instructions.md`
    : ".agsync/instructions.md";

  const lines: string[] = [];

  lines.push(`<!-- Generated by agsync. Edit: ${src} -->`);
  lines.push("");

  if (context.hld.trim()) {
    lines.push("## HLD");
    lines.push("");
    lines.push(context.hld.trim());
    lines.push("");
  }

  if (context.patterns.length > 0) {
    for (const patternId of context.patterns) {
      const def = patternDefs.find((p) => p.id === patternId);
      if (def?.hld) {
        lines.push(`## Pattern: ${patternId}`);
        lines.push("");
        lines.push(def.hld.trim());
        lines.push("");
      }
    }
  }

  if (context.guidelines.length > 0) {
    lines.push("## Guidelines");
    lines.push("");
    for (const g of context.guidelines) {
      const allGlobal = g.paths.length === 1 && g.paths[0] === "**";
      const pathNote = allGlobal ? "" : ` *(${g.paths.join(", ")})*`;
      lines.push(`- **[${g.id}]** ${g.rule}${pathNote}`);
    }
    lines.push("");
  }

  const relevantSkills = isRoot
    ? skills.filter((s) => !s.scope)
    : skills.filter((s) => s.scope === context.scope);
  const allScopedSkills = isRoot ? skills.filter((s) => s.scope) : [];

  lines.push("<!-- agsync:begin -->");
  lines.push("## Available Skills");
  lines.push("");

  for (const skill of relevantSkills) {
    lines.push(`- **${skill.name}**: ${skill.description}`);
  }

  if (allScopedSkills.length > 0) {
    const byScope = new Map<string, ResolvedSkill[]>();
    for (const skill of allScopedSkills) {
      const group = byScope.get(skill.scope!) ?? [];
      group.push(skill);
      byScope.set(skill.scope!, group);
    }
    for (const [scope, group] of byScope) {
      lines.push("");
      lines.push(`### Scope: \`${scope}\``);
      lines.push("");
      for (const skill of group) {
        lines.push(`- **${skill.name}**: ${skill.description}`);
      }
    }
  }

  if (scopeRefs.length > 0) {
    lines.push("");
    lines.push("## Scoped Instructions");
    lines.push("");
    for (const ref of scopeRefs) {
      lines.push(`- When working in folder: \`${ref}\` — you MUST load \`${ref}/AGENTS.md\``);
    }
  }

  lines.push("");
  lines.push("Skills are managed by agsync. Full definitions are in `.agents/skills/`.");
  lines.push("<!-- agsync:end -->");

  return lines.join("\n") + `\n<!-- DO NOT EDIT THIS FILE. Edit: ${src} -->\n`;
}
